global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer.nap"
    static_configs:
      - targets: ["napier.orderer.ac.uk:9443"]
  - job_name: "orderer.edin"
    static_configs:
      - targets: ["edincollege.orderer.ac.uk:9440"]
  - job_name: "peer0_nap"
    static_configs:
      - targets: ["peer0.napier.ac.uk:7051"]
  - job_name: "peer1_nap"
    static_configs:
      - targets: ["peer1.napier.ac.uk:7052"]
  - job_name: "peer0_edin"
    static_configs:
      - targets: ["peer0.edincollege.ac.uk:8051"]
  - job_name: "peer1_edin"
    static_configs:
      - targets: ["peer1.edincollege.ac.uk:8052"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
